'''create_tree.py creates md5 checksums for all files in a folder and subfolders.

This script generates an indexed md5 checksum for every file in the directory.
It does not verify checksums. Please see verify_tree.py for verification.
'''

import hashlib
import multiprocessing
import os
import sys

py_version = sys.version_info.major

def make_full_file_list(dir1):
    '''I find all the files in the directory and sub-folders.
       I am not in create.py'''
    file_list = []
    for root, dirs, files in os.walk(dir1):
        for f in files:
            file_list.append(os.path.join(root, f))
    return file_list

def md5_for_file(f, block_size=2**20):
    '''This function, md5_for_file was copied from StackOverflow, used under the
    Creative Commons license outlined at:
    http://blog.stackoverflow.com/2009/06/attribution-required/

    StackOverflow User Yuval Adam.
    http://stackoverflow.com/users/24545/yuval-adam
    Code:
    http://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python#1131238
    '''
    m = hashlib.md5()
    with open(f, "rb") as f:
        while True:
            buf = f.read(block_size)
            if not buf:
                break
            m.update(buf)
    return m.hexdigest()

def prep_for_writing(f):
    if not f:
        return None
    new = f+'.md5'
    if '.DS_Store' in f: return None
    if os.path.isfile(new): return None
    elif '.md5.' in new: return None
    else:
        write_md5_file(f, new)

def write_md5_file(f, new):
    try:
        print("Making MD5 for {} now.".format(f))
    except UnicodeEncodeError:
        print("Making MD5 for a file with special characters in its name now.")
        print("\n* * * * * * * * * * * * * * * * * * * * * * * *\n")
        print("  DOES THIS FILE WITH SPECIAL CHARACTERS IN\n")
        print("  ITS NAME NEED TO BE RENAMED?")
        print("  {}\n".format(f.encode()))
        print("* * * * * * * * * * * * * * * * * * * * * * * *\n")
    try:
        m = md5_for_file(f)
    except IOError:
        print("\n* * * * * * * * * * * * * * * * * * * * * * * *\n")
        print("An MD5 checksum cannot be generated for {} with this version of Python.".format(f.encode()))
        print("\n* * * * * * * * * * * * * * * * * * * * * * * *\n")
        return None

    if py_version == 2:
        with open(new, 'w') as n:
            n.write('; Generated by create.py\r\n')
            n.write('; You may find a copy at https://github.com/hooverinstitutionla/md5_utilities\r\n')
            n.write(m+' *'+f)
    else:
        with open(new, 'w', encoding='utf8') as n:
            n.write('; Generated by create.py\r\n')
            n.write('; You may find a copy at https://github.com/hooverinstitutionla/md5_utilities\r\n')
            n.write(m+' *'+f)

def main():
    folder = os.getcwd()
    full_files = make_full_file_list(folder)
    cores_count = multiprocessing.cpu_count()
    pool = multiprocessing.Pool(processes=cores_count)
    for f in pool.imap_unordered(prep_for_writing, full_files):
        prep_for_writing(f)

    print("\nDone!\n")


if __name__ == '__main__':
    main()
