#!/usr/bin/env python
#
# make_md5.py
# Author: Jim Sam
# This script generates an indexed md5 checksum for every file in the directory.
# It does not verify checksums.
#
# To use this:
# 1. add this file to the home directory. (House icon in Finder)
# 2. Open Terminal (Applications > Utilities > Terminal)
# 3. navigate to the folder you want to process
# 4. type "python ~/make_md5.py"
# 5. hit enter.
#

import os
import hashlib

# This function, md5_for_file was copied from StackOverflow. Please see:
# http://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python#1131238
def md5_for_file(f, block_size=2**20):
    m = hashlib.md5()
    with open(f, "rb" ) as f:
        while True:
            buf = f.read(block_size)
            if not buf:
                break
            m.update( buf )
    return m.hexdigest()

def main():
    this_dir = os.listdir('.')

    for i in this_dir:
        new = i+'.md5'
        if os.path.isfile(new):
            continue
        elif '.md5.' in new:
            continue
        else:
            print("Making MD5 for %s now." % i)
            m = md5_for_file(i)
            # yo = f.read()
            # m.update(yo)
            j = open(new, 'w')
            j.write('; Generated by make_md5.py\n')
            j.write(m+' *'+i)
            j.close()

    print("\nDone!\n")


if __name__ == '__main__':
    main()
